# Generated by Django 4.0.10 on 2024-03-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
