# Generated by Django 4.0.10 on 2024-03-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0002_alter_reciever_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='content',
            name='charset',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='email_address',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='message',
        ),
        migrations.DeleteModel(
            name='Charset',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Content_Type',
        ),
        migrations.DeleteModel(
            name='Email_address',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Reciever',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
