# Generated by Django 5.0.3 on 2024-03-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appli_visualisation.category'),
        ),
    ]
