# Generated by Django 5.0.3 on 2024-04-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0010_remove_content_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.IntegerField(default=0),
        ),
    ]
