# Generated by Django 5.0.3 on 2024-04-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0011_message_conversation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation_id',
        ),
    ]
