# Generated by Django 5.0.3 on 2024-04-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0013_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_address',
            name='email_address_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
