# Generated by Django 5.0.3 on 2024-04-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0014_alter_email_address_email_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_address',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appli_visualisation.employee'),
        ),
    ]
