# Generated by Django 5.0.3 on 2024-04-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0016_alter_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_address',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appli_visualisation.employee'),
        ),
    ]
