# Generated by Django 5.0.3 on 2024-04-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0017_alter_email_address_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_address',
            name='email_address_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
