# Generated by Django 5.0.3 on 2024-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_visualisation', '0018_alter_email_address_email_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_address',
            name='email_address_name',
            field=models.CharField(max_length=115, unique=True),
        ),
    ]
